services:
  - type: web
    name: inventory-app
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    # 아래 startCommand가 더 안정적인 방식으로 수정되었습니다.
    startCommand: "python -m streamlit run app.py"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: inventory-db
          property: internalConnectionString