services:
  - type: web
    name: inventory-app
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: inventory-db # 렌더에서 만든 데이터베이스 이름과 일치해야 합니다.
          property: internalConnectionString